version: 2.1

orbs:
  coveralls: coveralls/coveralls@1.0.6

executors:
  ruby-base:
    docker:
      - image: circleci/ruby:2.6.5-node
        environment:
          RAILS_ENV: test

jobs:
  build-and-test:
    executor: ruby-base
    steps:
      - checkout
      - run:
          name: install bundler
          command: gem install bundler
      - run:
          name: Which bundler?
          command: bundle -v
      - restore_cache:
          keys:
            - gem-cache-{{ checksum "Gemfile.lock" }}
      - run: bundle install --path vendor/bundle
      - save_cache:
          key: gem-cache-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run:
          name: install gems
          command: bundle install
      - run:
          name: run dummy test
          command: bundle exec rails test
      - coveralls/upload:
          path_to_lcov: ./coverage/lcov/project.lcov


workflows:
  version: 2
  build-test:
    jobs:
      - build-and-test
